########################################################################
#                      MarkdownLint Configuration                      #
#                                                                      #
# This file controls a Markdown linter used to govern prose in the     #
# project. See <https://github.com/DavidAnson/vscode-markdownlint> for #
# more details.                                                        #
########################################################################

# Allow identical headings as long as they are not siblings.
MD024:
  siblings_only: true
MD033:
  allowed_elements:
    - div
    - span
    - style
    - sub
    - sup
