########################################################################
#                         Clippy Configuration                         #
#                                                                      #
# This file controls the `cargo clippy` linter for the lints where it  #
# accepts external input. Relatively few lints do; most require        #
# attributes set directly in the source code.                          #
########################################################################

msrv = "1.56.0"
single-char-binding-names-threshold = 8
too-many-arguments-threshold = 8
